services:
  flask:
    env_file:
    - .env.dev
    container_name: flask-app
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - WSGI_HOST=0.0.0.0
      - PORT=5000
      - env_file=.env.dev
    volumes:
      - ${MOUNT_PATH_MAIN}:/app

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - ${MOUNT_PATH_MAIN}/cronjob.log:/app/cronjob.log
